"""add_role_to_user_and_make_tenant_nullable

Revision ID: f26ec1cce344
Revises: b1402fea3d29
Create Date: 2025-10-23 12:44:12.802945

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f26ec1cce344"
down_revision: Union[str, Sequence[str], None] = "b1402fea3d29"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    userroletype = sa.Enum(
        "SUPER_ADMIN", "TENANT_ADMIN", "TENANT_USER", name="userrole"
    )
    userroletype.create(op.get_bind())
    op.add_column(
        "user",
        sa.Column("role", userroletype, nullable=False, server_default="TENANT_USER"),
    )
    op.alter_column("user", "tenant_id", existing_type=sa.UUID(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user", "tenant_id", existing_type=sa.UUID(), nullable=False)
    op.drop_column("user", "role")
    userroletype = sa.Enum(
        "SUPER_ADMIN", "TENANT_ADMIN", "TENANT_USER", name="userrole"
    )
    userroletype.drop(op.get_bind())
    # ### end Alembic commands ###
